name: Run Jupyter Notebook

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set  up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install jupyter nbconvert

      - name: Run Notebook and Generate HTML
        run: |
          jupyter nbconvert los_angeles_homicides.ipynb --to html

        - name: Commit HTML output
          uses: stefanzweifel/git-auto-commit-action@v5
          with:
            commit_message: "Updated HTML output"
