name: Run Jupyter Notebook

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set  up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install jupyter nbconvert

      - name: Run all notebooks and convert to HTML
        run: |
          mkdir -p html
          export FROM_NBCONVERT=true
          for notebook in *.ipynb; do
            jupyter nbconvert "$notebook" --to html --output-dir="./html" --execute
          done

      - name: Commit HTML output
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "bot@github.com"
          git add .
          git commit -m "Updated by github action"
          git push
